### ISSUE TITLE
Streamed .root file closed during `uproot.iterate`

### ISSUE THREAD

**Issue by tvoigtlaender** [scikit-hep/uproot5#709] opened 2022-09-12 13:23 UTC
Hello, 

I am currently experiencing an issue related to `uproot.iterate` of streamed `.root` files.

It seems that the streamed file is not always kept open until all data is used up, leading to a `ValueError: I/O operation on closed file` error. There was no issue when reading the same file from a local directory.
With the setup as shown below, the error occurs in about 10% of the runs. It is likely that this number is dependent on the available memory of the machine. 
When we lowered the amount of data in each batch from 100 KB to just 10 KB, the issue happened in 100% of runs.
As the way, the events are processed is quite memory intensive, the small data batches (100 KB) are necessary.

I am not sure if the issue lies with uproot, XRootD, the small size of the used data batches or the way the root file was created.

Best regards,
Tim

The file used in the example:
https://www.dropbox.com/s/ztw85ira3o8kz0z/2018_mt_emb_emb_datashard_fold0.root?dl=0

The issue was experienced with python 3.10, uproot 4.3.5 and XRootD 5.5.0

The testing script:
```python
import uproot
print(uproot.__version__)

path_local = "2018_mt_emb_emb_datashard_fold0.root"
path_remote = "root://cmsxrootd-kit-disk.gridka.de//store/user/tvoigtlaender/uproot_issue/2018_mt_emb_emb_datashard_fold0.root"

variables = ["pt_1", "pt_2", "m_vis", "njets", "jpt_1", "jpt_2"]

print("\nTest with local file")
for i, vals in enumerate(uproot.iterate(path_local, expressions=variables, library="np", step_size="100 KB")):
    print("Events in batch {}: {}".format(i, len(vals[variables[0]])))

print("\nTest with remote file")
for i, vals in enumerate(uproot.iterate(path_remote, expressions=variables, library="np", step_size="100 KB")):
    print("Events in batch {}: {}".format(i, len(vals[variables[0]])))
```
The error:
```python
Traceback (most recent call last):
  File "/work/tvoigtlaender/uproot_issue/test.py", line 14, in <module>
    for i, vals in enumerate(uproot.iterate(path_remote, expressions=variables, library="np", step_size="100 KB")):
  File "/work/tvoigtlaender/uproot_issue/miniconda/envs/test_env/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 190, in iterate
    for item in hasbranches.iterate(
  File "/work/tvoigtlaender/uproot_issue/miniconda/envs/test_env/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 1488, in iterate
    _ranges_or_baskets_to_arrays(
  File "/work/tvoigtlaender/uproot_issue/miniconda/envs/test_env/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 3405, in _ranges_or_baskets_to_arrays
    hasbranches._file.source.chunks(ranges, notifications=notifications)
  File "/work/tvoigtlaender/uproot_issue/miniconda/envs/test_env/lib/python3.10/site-packages/uproot/source/xrootd.py", line 371, in chunks
    status = self._resource.file.vector_read(
  File "/work/tvoigtlaender/uproot_issue/miniconda/envs/test_env/lib/python3.10/site-packages/XRootD/client/file.py", line 236, in vector_read
    return XRootDStatus(self.__file.vector_read(chunks, timeout, callback))
ValueError: I/O operation on closed file
```

**Comment by mschnepf** [comment] 2023-07-26 11:55
Are there any updates about that bug?

**Comment by ioanaif** [comment] 2024-02-21 13:48
Hi @tvoigtlaender! 

Does the remote path still host the file? I cannot reproduce the same error you are showing. I am getting a file not found error: file not found ([FATAL] Invalid address)

**Comment by tvoigtlaender** [comment] 2024-02-21 15:52
Hi,

there have been some changes to the naming since then.
The same file is now located at 
`root://cmsxrootd-kit-disk.gridka.de//store/user/tvoigtlaender/uproot_issue/2018_mt_emb_emb_datashard_fold0.root`
For the comparison to the local results, the file also needs to be present in the directory from which you are running the provided test.

I just tested it (this time with python 3.9.18 and uproot 5.0.13) and still got the same error.

**Comment by ioanaif** [comment] 2024-02-27 11:19
Hi @tvoigtlaender!

I don't have access to that server so I can test this. 

I've just added an option https://github.com/scikit-hep/uproot5/pull/1146 to specify the `max size of the header bytes` when reading over `http` which solved another issue that had the server closing the connections when trying to read big chunks of data. https://github.com/scikit-hep/uproot5/issues/881

I am wondering if this might be the same issue. 

Could you please test this by opening the file with the `http` handler and limit the `http_max_header_bytes` if there's a need?

```
f = uproot.open(
        path_remote, handler=uproot.source.http.HTTPSource, http_max_header_bytes=21786
    )
```

**Comment by ioanaif** [comment] 2024-02-29 15:07
I believe this issue has been fixed through https://github.com/scikit-hep/uproot5/pull/1146 

If I am wrong about it being fixed, please do make the remote file available and comment on this issue and we will re-open it.

**Closed by ioanaif** 2024-02-29 15:07 UTC
Labels: bug (unverified)
