### ISSUE TITLE
Crash when reading remote file

### ISSUE THREAD

**Issue by wiso** [scikit-hep/uproot5#896] opened 2023-05-25 10:09 UTC
Hello, I am using uproot 4.3.7 and it crashed when reading a remote file.

Actually this problem started on the ROOT forum, since when plotting a single variable from a TTree from a remote files it tooks several minutes, while locally less then a second. The file is really small 4.5M

https://root-forum.cern.ch/t/reading-from-http-very-slow/53213/26

```
time python -c "import uproot; uproot.open('https://cernbox.cern.ch/remote.php/dav/public-files/1Cy1HIf03Ca76Dm/test_ntuples_200123.root').get('Electrons_All').arrays('pt__NOSYS')"

    raise uproot.deserialization.DeserializationError(
uproot.deserialization.DeserializationError: while reading

    TBasket version None as uproot.models.TBasket.Model_TBasket (? bytes)
        fNbytes: 218759168
        fObjlen: 65798144
        fDatime: 293105760
        fKeylen: 32314
        fCycle: 85
Members for TBasket: fNbytes?, fObjlen?, fDatime?, fKeylen?, fCycle?

attempting to get bytes 38380:38398
outside expected range 6085:8333 for this Chunk
in file https://cernbox.cern.ch/remote.php/dav/public-files/1Cy1HIf03Ca76Dm/test_ntuples_200123.root

```

it is curious that if I read if from elsewhere it works

```
time python -c "import uproot; uproot.open('http://rgw.fisica.unimi.it/test-ruggero/test_ntuples_200123.root?AWSAccessKeyId=M06HBTUGIKXVXYH1RES6&Signature=hpX%2FNzIKINZd825AWEGw%2FuVQ4nU%3D&Expires=1693581796').get('Electrons_All').arrays('pt__NOSYS')"
```

you can download the root file locally from these url.

**Comment by ioanaif** [comment] 2023-07-06 17:17
Hi!   

The crash happens when the file is hosted on `cernbox`, however it does work when hosted elsewhere (I alos tested this from my own cernbox). Thus, it seems as though this is a `cernbox` issue and not an `uproot` issue.

**Comment by wiso** [comment] 2023-07-06 19:29
Hello, as written originally this problem started on the ROOT forum, since the reading is very slow. The thread is very long and it seems related to an issue of the http server serving the file from cernbox. There is also a jira https://github.com/root-project/root/issues/13018.

By the way, with ROOT it is slow, but it works.

**Comment by jpivarski** [comment] 2023-07-06 19:43
I was able to pull all of the TBasket data (individually) with

```python
>>> import uproot
>>> f = uproot.open("https://cernbox.cern.ch/remote.php/dav/public-files/1Cy1HIf03Ca76Dm/test_ntuples_200123.root")
>>> t = f["Electrons_All"]
>>> baskets = []
>>> for i in range(t["pt__NOSYS"].num_baskets):
...     basket = t["pt__NOSYS"].basket(i)
...     baskets.append(basket)
...     print(i, basket)
... 
0 <TBasket 0 of 'pt__NOSYS' at 0x7f953b4b2b50>
1 <TBasket 1 of 'pt__NOSYS' at 0x7f953b4b2af0>
2 <TBasket 2 of 'pt__NOSYS' at 0x7f953b4b2a90>
3 <TBasket 3 of 'pt__NOSYS' at 0x7f953b4b2a30>
4 <TBasket 4 of 'pt__NOSYS' at 0x7f953b4b29d0>
5 <TBasket 5 of 'pt__NOSYS' at 0x7f953b4b28e0>
6 <TBasket 6 of 'pt__NOSYS' at 0x7f953b4b2850>
...
# restarted it when there was a socket timeout at basket 271
...
297 <TBasket 297 of 'pt__NOSYS' at 0x7f953b3bcca0>
298 <TBasket 298 of 'pt__NOSYS' at 0x7f953b3bcd30>
299 <TBasket 299 of 'pt__NOSYS' at 0x7f953b3bcee0>
```

Because it's jagged data, I can't do `basket.array()` to test interpretations. None of them are oddly small:

```python
>>> [len(x.raw_data) for x in baskets]
[4472, 4576, 4640, 4440, 4496, 4816, 4600, 4592, 4688, 4600, 4528, 4672, 4688, 4680, 4536, 4616, 4536, 4456, 4648, 4528, 4656, 4768, 4368, 4640, 4720, 4784, 4824, 4760, 4656, 4560, 4800, 4640, 4560, 4632, 4776, 4848, 4648, 4640, 4576, 4544, 4664, 4472, 4520, 4472, 4728, 4800, 4536, 4712, 4704, 4408, 4720, 4512, 4528, 4624, 4760, 4560, 4480, 4640, 4776, 4752, 4616, 4600, 4576, 4600, 4784, 4568, 4808, 4608, 4632, 4624, 4680, 4624, 4728, 4664, 4568, 4544, 4688, 4680, 4728, 4712, 4768, 4480, 4688, 4680, 4568, 4744, 4744, 4464, 4712, 4512, 4696, 4712, 4632, 4688, 4672, 4600, 4840, 4520, 4712, 4480, 4632, 4592, 4560, 4616, 4680, 4656, 4744, 4528, 4624, 4760, 4680, 4552, 4688, 4632, 4664, 4624, 4632, 4512, 4728, 4616, 4712, 4712, 4760, 4536, 4776, 4632, 4688, 4560, 4656, 4800, 4632, 4600, 4648, 4608, 4744, 4496, 4464, 4744, 4776, 4640, 4608, 4440, 4568, 4576, 4816, 4512, 4576, 4760, 4728, 4584, 4480, 4720, 4608, 4672, 4640, 4832, 4576, 4664, 4600, 4688, 4752, 4808, 4656, 4760, 4664, 4720, 4424, 4696, 4648, 4656, 4632, 4624, 4584, 4792, 4552, 4576, 4728, 4672, 4640, 4576, 4512, 4680, 4728, 4720, 4792, 4672, 4680, 4720, 4712, 4688, 4584, 4528, 4672, 4624, 4712, 4736, 4696, 4672, 4456, 4456, 4688, 4648, 4536, 4672, 4688, 4552, 4632, 4592, 4568, 4664, 4544, 4552, 4696, 4600, 4488, 4592, 4640, 4592, 4576, 4648, 4408, 4544, 4800, 4656, 4584, 4688, 4536, 4800, 4792, 4632, 4792, 4768, 4592, 4728, 4648, 4736, 4744, 4528, 4592, 4824, 4688, 4472, 4640, 4576, 4480, 4576, 4640, 4704, 4768, 4584, 4680, 4752, 4560, 4832, 4456, 4736, 4616, 4768, 4592, 4568, 4504, 4584, 4544, 4760, 4648, 4912, 4544, 4664, 4616, 4632, 4696, 4680, 4488, 4480, 4800, 4712, 4808, 4544, 4632, 4560, 4808, 4696, 4472, 4704, 4560, 4640, 4704, 4632, 4656, 4640, 4808, 4480, 4648, 4568, 4776, 4664, 4640, 4728, 4576, 4672]
```

Maybe a smarter thing would be if I had run `TBranch.array` with `entry_start` and `entry_stop` set by `t["pt__NOSYS"].member("fBasketEntry")`. I suspect it's one bad TBasket.

Reading the first TBasket is fine:

```python
>>> t["pt__NOSYS"].array(entry_start=0, entry_stop=10)
<Array [[33.6, 17.1], [], ..., [50.3, 42.3], []] type='10 * var * float64'>
```

**Comment by jpivarski** [comment] 2023-08-03 13:58
I just tried reading the file locally, and there are no problems there, either:

```python
>>> import uproot
>>> f = uproot.open("test_ntuples_200123.root")
>>> f["Electrons_All"]["pt__NOSYS"].array()
<Array [[33.6, 17.1], [], ..., [], [63.4, 23.7]] type='60000 * var * float64'>
>>> f["Electrons_All"].arrays("pt__NOSYS")
<Array [{pt__NOSYS: [33.6, ...]}, ..., {...}] type='60000 * {pt__NOSYS: var...'>
```

So it works locally, it works through HTTP on the rgw.fisica.unimi.it server, but it just doesn't work on CERNBox. That seems to narrow it down to CERNBox, a server problem. It manifests itself as a deserialization error, but that's what would happen if a server returned wrong bytes.

Could this be taken up with CERNBox? (I'm wondering how we could provide them with a minimal reproducer. We'd want to show them how the bytes that come from one of the chunks is different when it's going through CERNBox than when it's going through rgw.fisica.unimi.it or local files.)

I'll be closing this here, though.

**Closed by jpivarski** 2023-08-03 13:58 UTC
Labels: bug (unverified)
