### ISSUE TITLE
Connection closed when reading big chunk of data over https

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot5#881] opened 2023-04-24 11:11 UTC
### Reproducing the issue

I ran into the following behavior while reading a ~3 GB remote file over https. When trying to read a modest number of columns all in one go, the following results in a `http.client.RemoteDisconnected`:

```python
import uproot

fname = "https://xrootd-local.unl.edu:1094//store/user/AGC/nanoAOD/TT_TuneCUETP8M1_13TeV"\
    "-powheg-pythia8/cmsopendata2015_ttbar_19980_PU25nsData2015v1_76X_mcRun2_asymptotic"\
    "_v12_ext3-v1_00000_0000.root"
arrays_to_read = ["Jet_mass", "nJet", "Muon_pt", "Jet_phi", "Jet_btagCSVV2", "Jet_pt", "Jet_eta"]
# arrays_to_read = ["Jet_mass", "nJet", "Muon_pt", "Jet_phi", "Jet_btagCSVV2", "Jet_pt"]  # this is ok

with uproot.open(fname) as f:
    f["Events"].arrays(arrays_to_read)
```

This is with Python 3.11.3 and `uproot` 5.0.7. Full traceback in details:

<details><summary>Details</summary>
<p>

```pytb
Traceback (most recent call last):
  File "[...]/test.py", line 31, in <module>
    f["Events"].arrays(arrays_to_read)
  File "[...]/python3.11/site-packages/uproot/behaviors/TBranch.py", line 836, in arrays
    _ranges_or_baskets_to_arrays(
  File "[...]/python3.11/site-packages/uproot/behaviors/TBranch.py", line 3147, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "[...]/python3.11/site-packages/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "[...]/python3.11/site-packages/uproot/behaviors/TBranch.py", line 3060, in chunk_to_basket
    basket = uproot.models.TBasket.Model_TBasket.read(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/site-packages/uproot/model.py", line 860, in read
    self.read_members(chunk, cursor, context, file)
  File "[...]/python3.11/site-packages/uproot/models/TBasket.py", line 228, in read_members
    ) = cursor.fields(chunk, _tbasket_format1, context)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/site-packages/uproot/source/cursor.py", line 194, in fields
    return format.unpack(chunk.get(start, stop, self, context))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/site-packages/uproot/source/chunk.py", line 417, in get
    self.wait(insist=stop)
  File "[...]/python3.11/site-packages/uproot/source/chunk.py", line 354, in wait
    self._raw_data = numpy.frombuffer(self._future.result(), dtype=self._dtype)
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/site-packages/uproot/source/futures.py", line 115, in result
    delayed_raise(*self._excinfo)
  File "[...]/python3.11/site-packages/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "[...]/python3.11/site-packages/uproot/source/http.py", line 304, in task
    response = connection[0].getresponse()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/http/client.py", line 1375, in getresponse
    response.begin()
  File "[...]/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

</p>
</details> 

### Other approaches and variations

Removing a column from the list, as in the commented out section, makes this run. It is surprisingly slow: these columns correspond to a few percent of the file content, and `["Jet_mass", "nJet", "Muon_pt", "Jet_phi", "Jet_btagCSVV2", "Jet_pt"]` still took me almost 9 minutes to read. Downloading the whole file is much faster (<1 minute). The crash itself (when requesting too many columns) is fast, it takes about 5 seconds for that to happen for me.

When running over the local file, reading all the initially intended columns (`["Jet_mass", "nJet", "Muon_pt", "Jet_phi", "Jet_btagCSVV2", "Jet_pt", "Jet_eta"]`) gives me a maximum RSS of around 800 MB. The `f.file.source.num_requested_bytes` comes out to around 150 MB, I assume the difference is coming from decompression.

I was wondering if somehow I run out of memory and that is what causes a crash that shows up as a misleading http error, but I would assume I have enough memory for that. I see similar behavior on a few different systems I have tried. I have also been in contact with the experts at UNL who see nothing suspicious on their end that might explain this. I was also wondering whether this is some kind of time-out, but 5 seconds total seems low for that.

A way I found to successfully read the data is to batch via `uproot.iterate`:
```python
for _ in uproot.iterate(f"{fname}:Events", expressions=arrays_to_read):
    pass
```

This works and is similarly slow to the non-batched version (~10 minutes). Setting `step_size` to a very large number to make this a single batch results in the same `http.client.RemoteDisconnected`.

Reading one column at a time in contrast is very fast, taking less than a minute with the remote file:
```python
with uproot.open(fname) as f:
    for arr in arrays_to_read:
        f["Events"].arrays(arr)
```
This also does not produce a crash for the full column list `["Jet_mass", "nJet", "Muon_pt", "Jet_phi", "Jet_btagCSVV2", "Jet_pt", "Jet_eta"]`.

### Impact

I am opening this as I am interested in better understanding the behavior, and to possibly flag it in case it is unexpected. This is not blocking me in any way, the `iterate` solution works fine (and should presumably generally be the better approach anyway). I am mainly curious about two things:
- What causes the `http.client.RemoteDisconnected`?
- Why is the reading of all columns at once (batched or not batched) so much slower than downloading the full file, or than reading one column at a time?

**Comment by jpivarski** [comment] 2023-04-24 14:42
> * What causes the `http.client.RemoteDisconnected`?

We just _use_ the standard library's `http.client` library; the error is coming from there, and presumably it means that the server decided to disconnect before the data could be fully downloaded. The last Uproot line in the stack trace is

https://github.com/scikit-hep/uproot5/blob/b53b16f3a47a8ef90374b54f34dae6d3e2bbc48b/src/uproot/source/http.py#L304

where we're just asking an `HTTPSConnection` object to `getresponse()` ([docs for that function](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection.getresponse)).

> * Why is the reading of all columns at once (batched or not batched) so much slower than downloading the full file, or than reading one column at a time?

I wonder if the following is happening: the file has a large number of TBaskets and Uproot is asking for them in concurrent threads, effectively attacking the server with many requests (one for each TBasket, from each of the threads) and the server gives up and starts closing connections. This could explain why it's slow and the slowness is proportionate to the number of TBranches requested (and therefore the number of TBaskets), and it could explain why the server is more likely to give up in such a case.

Ideally, Uproot batches all of the file byte ranges that it needs to read (one range of bytes for each TBasket) in a single request (using the [HTTPSource.chunks](https://github.com/scikit-hep/uproot5/blob/b53b16f3a47a8ef90374b54f34dae6d3e2bbc48b/src/uproot/source/http.py#L607-L632) method). Then the server responds with a [multipart range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#multipart_ranges), which [we parse](https://github.com/scikit-hep/uproot5/blob/b53b16f3a47a8ef90374b54f34dae6d3e2bbc48b/src/uproot/source/http.py#L389-L480) as a stream, putting the raw bytes for each TBasket onto a notification queue as it comes, and decompression/interpretation threads take them off the queue and work on them.

However, it's valid for an HTTP server to just not support multipart ranges. [When this happens](https://github.com/scikit-hep/uproot5/blob/b53b16f3a47a8ef90374b54f34dae6d3e2bbc48b/src/uproot/source/http.py#L357-L372), Uproot goes into a fallback mode ([MultithreadedHTTPSource](https://github.com/scikit-hep/uproot5/blob/b53b16f3a47a8ef90374b54f34dae6d3e2bbc48b/src/uproot/source/http.py#L707)), which launches [some number](https://github.com/scikit-hep/uproot5/blob/b53b16f3a47a8ef90374b54f34dae6d3e2bbc48b/src/uproot/reading.py#L187) of worker threads that each request one byte range/TBasket at a time, but keep the server busy by asking for them concurrently. However, as I said above, this could overwhelm the server. How many requests overwhelms the server depends entirely on the server—it's configured with its own thresholds. (If you can control the server, there's probably an "allow multipart GET" option, which might be turned off just because it was a default for the HTTP server software. It's not a very familiar/widely used part of the HTTP protocol; I've seen [some questions](https://stackoverflow.com/q/55665466/1623645) on StackOverflow just asking why it even exists.)

To determine if the scenario I described above is happening, there are a few things you can do:

  * Use [uproot.TBranch.num_baskets](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.TBranch.html#num-baskets) to find out how many baskets each requested TBranch has: this is the number of byte ranges Uproot will need to request.
  * Check the `f.file.source.fallback` (after attempting to read TBasket data) to see if the `HTTPSource` has switched over into fallback mode.
  * Check the server configuration to see if there's an easy way to turn on [multipart ranges](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#multipart_ranges). (That link goes to the Mozilla documentation, which uses standard terminology/words to search for.)
  * Reduce the `num_fallback_workers` in [uproot.open](https://uproot.readthedocs.io/en/latest/uproot.reading.open.html), though that won't help your performance problem.
  * Use XRootD? That shouldn't be the necessary solution, since HTTP (the protocol) can do this multipart-GET, but the equivalent in XRootD (called "vector_read") is much more common/familiar to servers.

**Comment by alexander-held** [comment] 2023-04-24 18:29
Thanks for all the info Jim! I will follow up with experts at UNL to understand whether anything can be changed on the side of the server. This sounds like `uproot` might just be behaving as expected.

The `num_baskets` per branch is around 200:
```
Jet_mass 212
nJet 194
Muon_pt 274
Jet_phi 212
Jet_btagCSVV2 212
Jet_pt 212
Jet_eta 212
```
I have no reference for that number, is this a lot? Over 1000 threads making a simultaneous request naively sounds like it could be a problem.

`f.file.source.fallback` is `None` after reading some data, assuming I am testing this correctly:
```python
import uproot

fname = "https://xrootd-local.unl.edu:1094//store/user/AGC/nanoAOD/TT_TuneCUETP8M1_13TeV"\
    "-powheg-pythia8/cmsopendata2015_ttbar_19980_PU25nsData2015v1_76X_mcRun2_asymptotic"\
    "_v12_ext3-v1_00000_0000.root"

with uproot.open(fname) as f:
    f["Events"]["nJet"]
    assert f.file.source.fallback is None
```
Does that imply that multipart ranges are actually supported? Perhaps expected compared with the previous test, but `num_fallback_workers=1` also does not change the behavior of `http.client.RemoteDisconnected` after a few seconds.

Switching to `root://` for reading can be a partial solution, it requires any valid certificate to read that way (while https requires nothing), I do not remember the reason but that is specific to the server and not easy to change from what I understand.

**Comment by jpivarski** [comment] 2023-04-24 21:19
> I have no reference for that number, is this a lot? Over 1000 threads making a simultaneous request naively sounds like it could be a problem.

200 TBaskets per TBranch in a reasonably large file, like 2 GB, sounds about right.

It would be 10 threads (`num_fallback_workers`) making over 1000 requests. Up to 10 requests can be in flight at any given time.

> `f.file.source.fallback` is `None` after reading some data, assuming I am testing this correctly:

That looks like a correct test to me, so I guess it's not going into the fallback. Therefore, you actually have 1 thread making a multi-part GET with thousands of byte ranges in it.

> A `Range` request with over 1024 items fails.

> Also, a `Range` request over ~19k characters fails with the server side immediately closing the connection.

I didn't know about these possible failure modes. In principle, Uproot ought to catch this and retry the request in smaller batches, but that will require significant new infrastructure: a fallback before the complete-fallback. Maybe if the HTTPSource (which attempts multi-part GET) can recognize that the `Range` requests are too long, it could split itself into two HTTPSources on different threads? Or would two requests for 1024 items each have to be sequential (i.e. don't request the second until the first has fully responded)? The concurrent one would be easier to write...

Is there a way to recognize this situation of the request being too long as distinct from the server just not accepting multi-part GET at all (and therefore know _which_ fallback to fall back to)?

**Comment by jthiltges** [comment] 2023-04-24 22:35
> Maybe if the HTTPSource (which attempts multi-part GET) can recognize that the Range requests are too long, it could split itself into two HTTPSources on different threads? Or would two requests for 1024 items each have to be sequential (i.e. don't request the second until the first has fully responded)?

That sounds reasonable to me. I'm not an XRootD expert, but would believe multiple simultaneous requests will be fine. I'm guessing we're just running into guardrails around its parsing of HTTP headers.

> Is there a way to recognize this situation of the request being too long as distinct from the server just not accepting multi-part GET at all (and therefore know which fallback to fall back to)?

Would limiting the request size and count to a reasonable default be enough? If the request fails, assume multi-part is not supported.

**Comment by jpivarski** [comment] 2023-04-25 13:22
@alexander-held can quickly work around it by putting fewer TBranches in his `arrays` request, and then joining them with `ak.zip` if need be. I think he raised this issue because it's something that's not _supposed_ to happen.

**Comment by alexander-held** [comment] 2023-04-25 13:36
Indeed, this is not blocking my work. I wanted to understand if everything is working as expected or if there is an action that should be taken somewhere. I imagine that the behavior might look confusing to other people as well (just as it was confusing for me).

If the server configuration is "normal" and other people may run into similar issues with other files, it might be useful to have some extra context in the exception. Not clear to me if that is potentially more confusing than helpful though if there are other likely sources of it being raised. At least if someone faces this, makes it to the issue tracker and search for `RemoteDisconnected`, now they will find this, so perhaps that can already help a bit.

**Comment by jpivarski** [comment] 2023-04-25 15:36
We _do_ often get bug reports about remote server issues, though more often with XRootD. Usually, I think we can't solve them because it's outside of Uproot's control, but this is an example of something that Uproot can do something about.

The main thing that we'll need, though, is a clear way to determine that the list of byte ranges was too long (and that's why it failed) or is going to be too long (and we shouldn't send it, because it will fail), so that Uproot can break down one thread sending a long request into N threads, each sending a reasonably long request. All the infrastructure is ready to accept the responses in parallel.

**Comment by jthiltges** [comment] 2023-04-25 20:15
There are certainly issues that XRootD HTTP needs to fix: returning a TCP RST, rather than an HTTP error. And returning a 206, then a spurious 500 failure immediately after. I'll try to get that into an issue on the XRootD side.

On the Uproot side of things, I'd guess it might be challenging to detect the error and adjust. Might get a 413, 431, or even a generic 400 or 500 error.

From searching, it looks like the [Apache default](https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestfieldsize) for header fields is 8190 bytes. And it seems widespread support for lengths beyond 16k is unusual. Would breaking requests into ~7.5k chunks be a good-enough solution?

**Comment by jpivarski** [comment] 2023-04-25 21:08
We can adapt Uproot to the way it should be, rather than the way it is now, since the course of action would be to upgrade software in either case. (Though I suppose that upgrading server software is more difficult and may be out of an individual's control.)

A configurable limit on the number of request bytes, default at 8190, before splitting into multiple requests is something we can do. I like this solution because it means we don't need to recognize a new type of server response. If there are any servers with this limit set below the default, it would be hard to debug, but an Uproot user who knows what the problem is can adjust the limit.

I'll turn this issue into a feature request.

**Comment by masonproffitt** [comment] 2023-05-01 09:34
One interesting note here: I can reproduce the original error here with `https://xrootd-local.unl.edu:1094`, but not with a locally running installation of the same XRootD version (5.5.4). The local version is slower than it should be due to https://github.com/xrootd/xrootd/issues/1976 and https://github.com/xrootd/xrootd/issues/2003, but it still works and doesn't raise the `RemoteDisconnected` exception. I wonder if there's a timeout or some XRootD config setting that's different on the UNL server.

**Closed** 2024-02-27 10:53 UTC
Labels: feature
