### ISSUE TITLE
uproot.dask with library='np' does not work as expected

### ISSUE THREAD

**Issue by oksuzian** [scikit-hep/uproot5#811] opened 2023-01-05 06:00 UTC
Hello,

I'm using uproot.dask routine to process root files.
It works fine with library='ak', and it works 'np' with 1D array.
However, it breaks for multidimensional arrays.
Please see an example below.

   --Yuri.

```
>>> uproot.__version__
'5.0.2'

dd_run = uproot.dask(file_list,  library='np')
dd_run['temperature'].compute()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[41], line 1
----> 1 dd_run['temperature'].compute()

File ~/.conda/envs/MyEnv/lib/python3.10/site-packages/dask/base.py:315, in DaskMethodsMixin.compute(self, **kwargs)
    291 def compute(self, **kwargs):
    292     """Compute this dask collection
    293 
    294     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    313     dask.base.compute
    314     """
--> 315     (result,) = compute(self, traverse=False, **kwargs)
    316     return result

File ~/.conda/envs/MyEnv/lib/python3.10/site-packages/dask/base.py:601, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    598     postcomputes.append(x.__dask_postcompute__())
    600 results = schedule(dsk, keys, **kwargs)
--> 601 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/.conda/envs/MyEnv/lib/python3.10/site-packages/dask/base.py:601, in <listcomp>(.0)
    598     postcomputes.append(x.__dask_postcompute__())
    600 results = schedule(dsk, keys, **kwargs)
--> 601 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/.conda/envs/MyEnv/lib/python3.10/site-packages/dask/array/core.py:1282, in finalize(results)
   1280 while isinstance(results2, (tuple, list)):
   1281     if len(results2) > 1:
-> 1282         return concatenate3(results)
   1283     else:
   1284         results2 = results2[0]

File ~/.conda/envs/MyEnv/lib/python3.10/site-packages/dask/array/core.py:5291, in concatenate3(arrays)
   5289         while arr.ndim < ndim:
   5290             arr = arr[None, ...]
-> 5291     result[idx] = arr
   5293 return result

ValueError: could not broadcast input array from shape (31006,6,64) into shape (31006,)
```

**Comment by ioanaif** [comment] 2023-02-23 15:15
Hi @oksuzian! 

Could you please provide a test file for this issue? I could not replicate it when testing with a 3D array.

**Comment by jpivarski** [comment] 2024-01-30 15:34
I'm closing this because it's over a year old and we can't proceed without a test file. Also, `uproot.dask` has changed a lot in that time; maybe it works now.

If this is still an issue, ask to have the issue reopened (with a file that we can use to reproduce it). Thanks!

**Closed by jpivarski** 2024-01-30 15:34 UTC
Labels: bug (unverified), needs-test-file
